---
- name: Create shared tmpfs and mount at clients
  hosts: master
  remote_user: root
  gather_facts: false
  become: false
  vars:
    tmpfs_path: "/run/jenkins_locks"
    proxy: "http://192.168.122.1:13128"
  roles:
    - role: create_tmpfs
      config_file: "/etc/tmpfiles.d/jenkins_locks.conf"
      mount_point: "{{ tmpfs_path }}"
      uid: "root"
      gid: "root"
      mode: '0644'
      size: "10m"
    - role: export_fs_nfs
      proxy_url: "{{ proxy | default('') }}"
      mount_point: "{{ tmpfs_path }}"

- name: Create shared tmpfs and mount at clients
  hosts: slaves
  remote_user: root
  gather_facts: false
  become: false
  vars:
    tmpfs_path: "/run/jenkins_locks"
    proxy: "{{ proxy | default('') }}"
  roles:
    - role: mount_fs_nfs
      server: "{{ groups['master'][0] }}"
      share_name: "{{ tmpfs_path }}"
      mount_point: "{{ tmpfs_path }}"
      proxy_url: "{{ proxy | default('') }}"
